#!/usr/bin/env python3
"""
Diagnóstico rápido del filtro MA200
"""
print("="*80)
print("🔍 DIAGNÓSTICO: Estado del Filtro MA200")
print("="*80)
print()

print("📋 INFORMACIÓN IMPORTANTE:")
print()
print("Los stocks que reportaste aparecen en tus resultados:")
print("- PYPL (PayPal) - posición 12")
print("- CPRT (Copart) - posición 24")
print("- DIS (Disney) - posición 13")
print()
print("Y dices que 'no han parado de caer', lo que sugiere que están")
print("BAJO su MA200 pero aparecen en los resultados.")
print()

print("="*80)
print("🎯 PREGUNTAS DE DIAGNÓSTICO")
print("="*80)
print()

print("Por favor responde estas preguntas:")
print()
print("1️⃣  ¿En qué checkbox está el 'Filtro MA200 (Faber 2007)'?")
print("   a) ✅ MARCADO (activado)")
print("   b) ☐ DESMARCADO (desactivado)")
print()

print("2️⃣  ¿Ves la sección '💾 Gestión de Datos' en el sidebar?")
print("   a) ✅ SÍ, la veo")
print("   b) ❌ NO, no la veo")
print()

print("3️⃣  Si ves la sección '💾 Gestión de Datos', ¿qué dice el checkbox?")
print("   a) ✅ 'Usar caché de precios' está MARCADO")
print("   b) ☐ 'Usar caché de precios' está DESMARCADO")
print("   c) No veo esta sección")
print()

print("4️⃣  ¿Cuándo ejecutaste el screening que muestra estos resultados?")
print("   a) Hace menos de 1 hora")
print("   b) Hace más de 1 hora pero hoy")
print("   c) Ayer o antes")
print()

print("5️⃣  ¿Hiciste 'Reboot app' en Streamlit Cloud después del último commit?")
print("   a) ✅ SÍ, reinicié la app")
print("   b) ❌ NO, no he reiniciado")
print("   c) No estoy usando Streamlit Cloud (ejecuto localmente)")
print()

print("="*80)
print("💡 DIAGNÓSTICO AUTOMÁTICO")
print("="*80)
print()

print("Basándome en que estos stocks aparecen en tus resultados,")
print("lo MÁS PROBABLE es una de estas causas:")
print()

print("CAUSA #1: FILTRO MA200 DESACTIVADO (Probabilidad: 🔴 ALTA)")
print("-" * 70)
print("El checkbox 'Filtro MA200 (Faber 2007)' está DESMARCADO")
print()
print("✅ SOLUCIÓN:")
print("   1. En el sidebar de Streamlit")
print("   2. Busca la sección '🚀 Filtros Avanzados (NUEVO)'")
print("   3. MARCA el checkbox '✅ Filtro MA200 (Faber 2007)'")
print("   4. Re-ejecuta '🚀 Ejecutar Screening V3'")
print()

print("CAUSA #2: CACHE DESACTUALIZADO (Probabilidad: 🟡 MEDIA)")
print("-" * 70)
print("Los datos de precios están cacheados de hace días/semanas")
print("En ese momento, PYPL/CPRT/DIS estaban sobre MA200")
print("Pero HOY están bajo MA200")
print()
print("✅ SOLUCIÓN:")
print("   1. En el sidebar, busca '💾 Gestión de Datos'")
print("   2. DESMARCA el checkbox 'Usar caché de precios'")
print("   3. Haz clic en '🗑️ Limpiar Caché'")
print("   4. Re-ejecuta '🚀 Ejecutar Screening V3'")
print()

print("CAUSA #3: APP NO ACTUALIZADA (Probabilidad: 🟢 BAJA)")
print("-" * 70)
print("Streamlit Cloud no tiene los cambios más recientes")
print()
print("✅ SOLUCIÓN:")
print("   1. Ve a tu dashboard de Streamlit Cloud")
print("   2. Clic en 'Manage app'")
print("   3. Clic en 'Reboot app'")
print("   4. Espera 30-60 segundos")
print("   5. Re-ejecuta el screening")
print()

print("="*80)
print("🚀 ACCIÓN RECOMENDADA (HAZLO EN ORDEN)")
print("="*80)
print()

print("PASO 1: Verifica filtro MA200")
print("├─ Abre la app de Streamlit")
print("├─ En sidebar, sección '🚀 Filtros Avanzados'")
print("├─ Verifica que '✅ Filtro MA200 (Faber 2007)' esté MARCADO")
print("└─ Si no está marcado, MÁRCALO")
print()

print("PASO 2: Deshabilita cache")
print("├─ En sidebar, sección '💾 Gestión de Datos'")
print("├─ DESMARCA 'Usar caché de precios'")
print("├─ Debería aparecer un warning amarillo:")
print("│  '⚠️ Cache deshabilitado: Se descargarán datos frescos'")
print("└─ Haz clic en '🗑️ Limpiar Caché'")
print()

print("PASO 3: Re-ejecuta el screening")
print("├─ Haz clic en '🚀 Ejecutar Screening V3'")
print("├─ ESPERA (puede tomar más tiempo sin cache)")
print("└─ Verifica en la salida del PASO 7:")
print("   '✅ MA200 Filter: ENABLED (Faber 2007)'")
print("   '⚠️  Rechazados por MA200: X stocks'")
print()

print("PASO 4: Verifica resultados")
print("├─ Los stocks bajo MA200 NO deberían aparecer")
print("├─ PYPL, CPRT, DIS deberían estar AUSENTES")
print("└─ O aparecer con ❌ en la columna MA200")
print()

print("="*80)
print("📞 SI EL PROBLEMA PERSISTE")
print("="*80)
print()
print("Si después de hacer TODOS los pasos anteriores")
print("todavía ves PYPL/CPRT/DIS en los resultados:")
print()
print("1. Toma un screenshot de:")
print("   - La sección de filtros del sidebar")
print("   - Los resultados del PASO 7 en la salida")
print("   - La tabla con los stocks finales")
print()
print("2. Copia y pega la salida COMPLETA del PASO 7")
print()
print("3. Avísame y te ayudaré a investigar más a fondo")
print()
print("="*80)
