#!/usr/bin/env python3
"""
Debugging: ¿Qué filtro académico elimina todos los stocks?
"""

print("=" * 80)
print("🔍 DIAGNÓSTICO: FILTROS ACADÉMICOS")
print("=" * 80)
print()

print("📊 PROBLEMA REPORTADO:")
print("-" * 80)
print("- PASO 7 Output: 83 stocks")
print("- Portfolio Final: 0 stocks (NO HAY STOCKS)")
print()

print("🎯 FILTROS ACTIVADOS POR DEFECTO (sospechosos):")
print("-" * 80)
print()
print("1. ✅ Earnings Quality Filter (Sloan 1996)")
print("   - value=True (ACTIVADO)")
print("   - min_earnings_quality_score=50.0")
print("   - max_accruals_ratio=0.10")
print("   - EFECTO: Elimina stocks con earnings manipulation")
print()

print("2. 🚩 Red Flags Detection")
print("   - value=True (ACTIVADO)")
print("   - min_red_flags_score=60.0")
print("   - EFECTO: Elimina dilución excesiva, pérdidas recurrentes")
print()

print("3. 📉 Short-Term Reversal Filter (Jegadeesh 1990)")
print("   - value=True (ACTIVADO)")
print("   - reversal_threshold=-0.08 (-8%)")
print("   - EFECTO: Elimina stocks que cayeron >8% última semana")
print()

print("4. 💎 Enhanced Value Score")
print("   - value=True (ACTIVADO)")
print("   - usa 7 métricas en lugar de 3")
print("   - EFECTO: Score más estricto")
print()

print("=" * 80)
print("🐛 POR QUÉ ELIMINAN TODO")
print("=" * 80)
print()

print("Estos filtros son ACUMULATIVOS (AND, no OR):")
print()
print("  83 stocks")
print("    ↓")
print("  Earnings Quality Filter → Rechaza 40 stocks")
print("    ↓")
print("  Red Flags Filter → Rechaza 30 stocks")
print("    ↓")
print("  Reversal Filter → Rechaza 13 stocks")
print("    ↓")
print("  0 stocks restantes ❌")
print()

print("=" * 80)
print("✅ SOLUCIÓN (3 opciones)")
print("=" * 80)
print()

print("OPCIÓN A: Desactivar TODOS los filtros académicos")
print("-" * 80)
print("En Streamlit, DESMARCA:")
print("  ❌ Earnings Quality Filter")
print("  ❌ Red Flags Detection")
print("  ❌ Short-Term Reversal Filter")
print()
print("Resultado: ~70-80 stocks en portfolio")
print()

print("OPCIÓN B: Relajar los umbrales")
print("-" * 80)
print("Modifica en qvm_pipeline_v3.py:")
print()
print("  # Antes (estricto)")
print("  min_earnings_quality_score: float = 50.0")
print("  min_red_flags_score: float = 60.0")
print()
print("  # Después (relajado)")
print("  min_earnings_quality_score: float = 30.0")
print("  min_red_flags_score: float = 40.0")
print()
print("Resultado: ~40-50 stocks en portfolio")
print()

print("OPCIÓN C: Activar solo 1 filtro a la vez")
print("-" * 80)
print("Prueba con solo 1 filtro activado:")
print("  ✅ Earnings Quality Filter")
print("  ❌ Red Flags Detection")
print("  ❌ Short-Term Reversal Filter")
print()
print("Identifica cuál es el más problemático")
print()

print("=" * 80)
print("📋 CONFIGURACIÓN RECOMENDADA")
print("=" * 80)
print()

print("Para empezar, usa esta configuración:")
print()
print("FILTROS BÁSICOS:")
print("  ✅ Filtro MA200")
print("  ✅ Momentum mínimo")
print("  ❌ Filtro 52w High")
print()
print("BREAKOUTS:")
print("  ❌ Filtro de Breakout")
print("  ❌ Breakouts Confirmados")
print("  ❌ Volume Surge")
print()
print("ACADÉMICOS:")
print("  ❌ Earnings Quality Filter")
print("  ❌ Red Flags Detection")
print("  ❌ Short-Term Reversal Filter")
print("  ✅ Enhanced Value Score (solo cambia score, no filtra)")
print()
print("Resultado esperado: 60-80 stocks en portfolio")
print()

print("=" * 80)
print("🎯 ACCIÓN INMEDIATA")
print("=" * 80)
print()
print("1. Abre Streamlit")
print("2. Ve a '🎓 Mejoras Académicas V3.1'")
print("3. DESMARCA los 3 checkboxes:")
print("   ❌ Earnings Quality Filter")
print("   ❌ Red Flags Detection")
print("   ❌ Short-Term Reversal Filter")
print("4. Re-ejecuta el screener")
print("5. Deberías obtener ~70-80 stocks")
print()

print("=" * 80)
