#!/usr/bin/env python3
"""
Debug específico para PYPL y el filtro MA200
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import pandas as pd
from datetime import datetime, timedelta

print("="*80)
print("🔍 DIAGNÓSTICO: PYPL y Filtro MA200")
print("="*80)
print()

# Análisis de la lógica
print("📋 ANÁLISIS DE LA LÓGICA DEL FILTRO MA200:")
print()

print("1️⃣  DONDE SE APLICA EL FILTRO:")
print("   Archivo: qvm_pipeline_v3.py")
print("   Línea: 876-880")
print()
print("   Código:")
print("   ```python")
print("   if config.require_above_ma200:")
print("       df_merged = df_merged[df_merged['above_ma200'] == True].copy()")
print("   ```")
print()

print("2️⃣  COMO SE CALCULA above_ma200:")
print("   Archivo: momentum_calculator.py")
print("   Función: is_above_ma200(prices)")
print()
print("   Lógica:")
print("   - Obtiene precio actual: prices['close'].iloc[-1]")
print("   - Calcula MA200: prices['close'].rolling(200).mean().iloc[-1]")
print("   - Retorna: precio_actual > ma200")
print()

print("3️⃣  POSIBLES CAUSAS DEL PROBLEMA:")
print()

print("❌ CAUSA #1: Filtro NO activado")
print("   Verificar: En Streamlit, checkbox 'Filtro MA200' debe estar marcado")
print("   Síntoma: Si el usuario ve stocks bajo MA200 en resultados")
print("   Solución: Marcar el checkbox y re-ejecutar")
print()

print("❌ CAUSA #2: Datos de precios desactualizados (CACHÉ)")
print("   Problema: Los precios se obtienen con use_cache=True")
print("   Archivo: qvm_pipeline_v3.py línea 821")
print("   Código: prices = fetch_prices(symbol, start=..., end=..., use_cache=True)")
print()
print("   🚨 ESTE ES PROBABLEMENTE EL PROBLEMA!")
print()
print("   Si los datos fueron cacheados hace días/semanas:")
print("   - El precio 'actual' en el cache puede estar sobre MA200")
print("   - Pero el precio REAL de hoy puede estar BAJO MA200")
print("   - El usuario ve resultados desactualizados")
print()
print("   Solución:")
print("   - En Streamlit, clic en '🗑️ Limpiar Caché'")
print("   - Re-ejecutar el screener")
print()

print("❌ CAUSA #3: La columna 'above_ma200' no corresponde al filtro aplicado")
print("   Problema: La columna se calcula en PASO 7 pero se muestra sin verificar")
print("   Verificar: ¿Los datos en pantalla son del run actual o de un run anterior?")
print()

print("4️⃣  VERIFICACIÓN DIRECTA:")
print()
print("   Para verificar si PYPL está realmente sobre MA200 HOY:")
print()
print("   Option A - Con API key:")
print("   $ export FMP_API_KEY=tu_key")
print("   $ python3 quick_check_ma200.py")
print()
print("   Option B - Verificación manual:")
print("   1. Ir a https://finance.yahoo.com/quote/PYPL")
print("   2. Mirar el gráfico con MA200")
print("   3. Comparar precio actual vs MA200")
print()

print("5️⃣  SOLUCIÓN INMEDIATA:")
print()
print("   🎯 SI EL PROBLEMA ES CACHE (más probable):")
print("   1. Abrir app Streamlit")
print("   2. Clic en '🗑️ Limpiar Caché' en la barra lateral")
print("   3. Verificar que 'Filtro MA200' esté MARCADO")
print("   4. Ejecutar '🚀 Ejecutar Screening V3'")
print("   5. Verificar en la salida:")
print("      - '✅ PASO 7: Momentum + MA200 Filter'")
print("      - 'MA200 Filter: ENABLED'")
print("      - 'Rejected by MA200: X' (debe ser > 0)")
print()

print("   🎯 SI EL PROBLEMA PERSISTE:")
print("   1. El filtro puede necesitar modificación para forzar")
print("      recarga de datos sin cache")
print("   2. Reportar el issue con:")
print("      - Screenshot de la salida del PASO 7")
print("      - Lista de símbolos problemáticos")
print("      - Fecha/hora de ejecución")
print()

print("="*80)
print("📊 DATOS DE LA TABLA DEL USUARIO:")
print("="*80)
print()
print("Símbolos mencionados:")
print("- BRFS: ✅ (Row 0)")
print("- ZIM: ✅ (Row 1)")
print("- UNVR: ✅ (Row 2)")
print("- DFS: ✅ (Row 3)")
print("- SKX: ✅ (Row 4)")
print("- VRTV: ✅ (Row 5)")
print("- NCLH: ✅ (Row 6)")
print("- AEL: ✅ (Row 7)")
print("- DPM.TO: ✅ (Row 8)")
print("- PYPL: ✅ (Row 9) <-- Usuario dice que está BAJO MA200")
print("- K.TO: ✅ (Row 10)")
print("- DCP: ✅ (Row 11)")
print("- SWI: ✅ (Row 12)")
print("- AMK: ✅ (Row 13)")
print("- IBTX: ✅ (Row 14)")
print()
print("Todos muestran ✅ en la columna above_ma200")
print()

print("="*80)
print("🔬 HIPÓTESIS PRINCIPAL:")
print("="*80)
print()
print("CACHE DE DATOS DESACTUALIZADOS")
print()
print("Razón:")
print("- El pipeline usa use_cache=True al descargar precios")
print("- Si los datos fueron cacheados hace días/semanas:")
print("  * En ese momento, PYPL estaba sobre MA200 → ✅")
print("  * Hoy, PYPL está bajo MA200")
print("  * Pero el usuario ve datos del cache antiguo")
print()
print("Evidencia:")
print("- Usuario dice 'PYPL no ha hecho más que estar estancada'")
print("- Esto sugiere que PYPL ha tenido mala performance recientemente")
print("- Podría haber caído bajo MA200 recientemente")
print()
print("✅ SOLUCIÓN: Limpiar cache y re-ejecutar")
print()
print("="*80)
