#!/usr/bin/env python3
"""
Diagnóstico: ¿Por qué el filtro MA200 rechaza tantos stocks?

Análisis del problema reportado:
- Input: 155 stocks
- Rejected by MA200: 69 (44.5%)
- Output: 83 stocks

¿Es esto normal? ¿Está filtrando correctamente?
"""

print("=" * 80)
print("🔍 ANÁLISIS DEL FILTRO MA200")
print("=" * 80)
print()

print("📊 DATOS REPORTADOS:")
print("-" * 80)
print(f"Input al PASO 7:        155 stocks")
print(f"Rejected by MA200:      69 stocks (44.5%)")
print(f"Rejected by Momentum:   3 stocks (1.9%)")
print(f"Output final:           83 stocks (53.5%)")
print()

print("=" * 80)
print("🤔 INTERPRETACIÓN")
print("=" * 80)
print()

print("1️⃣  ¿Es normal que 44.5% estén bajo MA200?")
print()
print("   ✅ SÍ, es completamente normal.")
print()
print("   En mercados típicos:")
print("   - Tendencia alcista: 60-70% sobre MA200")
print("   - Mercado lateral:   40-60% sobre MA200")
print("   - Tendencia bajista: 20-40% sobre MA200")
print()
print("   Si 55.5% pasaron el filtro (86/155), estamos en:")
print("   → Mercado LATERAL o inicio de recuperación")
print()

print("2️⃣  ¿El filtro está funcionando correctamente?")
print()
print("   Para verificarlo, necesitamos saber:")
print()
print("   A) ¿Cuántos del universo TOTAL están sobre MA200?")
print("      - Si universo = 800 stocks")
print("      - Y solo 155 llegaron al PASO 7")
print("      - Ya hubo mucho filtrado previo")
print()
print("   B) ¿Los 69 rechazados están REALMENTE bajo MA200?")
print("      - Esto requiere verificación con datos actuales")
print()

print("=" * 80)
print("🎯 POSIBLES PROBLEMAS")
print("=" * 80)
print()

print("Escenario A: FUNCIONAMIENTO NORMAL")
print("-" * 80)
print("✅ El mercado está lateral/bajista")
print("✅ Muchos stocks están bajo MA200 (normal)")
print("✅ El filtro está haciendo su trabajo")
print()
print("Solución: Ninguna, es el comportamiento esperado")
print()

print("Escenario B: DATOS DESACTUALIZADOS")
print("-" * 80)
print("⚠️  Los datos de MA200 son viejos")
print("⚠️  Stocks que YA están sobre MA200 se marcan como bajo")
print("⚠️  El caché tiene datos de hace días/semanas")
print()
print("Solución:")
print("  1. Haz clic en '🗑️ Limpiar Caché'")
print("  2. Re-ejecuta el screener")
print("  3. Verifica que 'last_date' en datos sea reciente")
print()

print("Escenario C: FILTRO MA200 DEMASIADO ESTRICTO")
print("-" * 80)
print("⚠️  Quieres TODOS los stocks, no solo sobre MA200")
print("⚠️  El filtro está activado pero no lo quieres")
print()
print("Solución:")
print("  1. Desmarca el checkbox 'Filtro MA200'")
print("  2. Verás TODOS los stocks (155 → 152 después de momentum)")
print("  3. La columna 'above_ma200' seguirá presente para referencia")
print()

print("Escenario D: BREAKOUT FILTER NO SE ESTÁ APLICANDO")
print("-" * 80)
print("⚠️  Activaste el filtro de breakout pero no aparece en logs")
print("⚠️  El PASO 8 no muestra métricas de breakout")
print()
print("Solución:")
print("  1. Verifica que 'enable_breakout_filter' esté marcado")
print("  2. Busca en la salida el PASO 8")
print("  3. Debe decir 'Breakouts detectados (últimos 5 días)'")
print()

print("=" * 80)
print("📋 ACCIONES RECOMENDADAS")
print("=" * 80)
print()

print("1. VERIFICA EL ESTADO DEL MERCADO:")
print("   - ¿Estamos en tendencia alcista o bajista?")
print("   - Si es bajista, es normal que muchos estén bajo MA200")
print()

print("2. VERIFICA LA CONFIGURACIÓN:")
print("   - ¿Tienes el checkbox 'Filtro MA200' marcado?")
print("   - Si NO lo quieres, desmárcalo")
print("   - Si SÍ lo quieres, está funcionando correctamente")
print()

print("3. VERIFICA LOS DATOS:")
print("   - Limpia el caché")
print("   - Re-ejecuta")
print("   - Verifica que la fecha de los datos sea reciente")
print()

print("4. MUÉSTRAME LA SALIDA COMPLETA:")
print("   - Copia TODO desde PASO 1 hasta PASO 10")
print("   - Especialmente PASO 7 y PASO 8")
print("   - Así puedo ver qué está pasando exactamente")
print()

print("=" * 80)
print("🔧 DEBUGGING RÁPIDO")
print("=" * 80)
print()

print("Ejecuta este comando para ver qué % del universo está sobre MA200:")
print()
print("  python3 -c \"")
print("  from data_fetcher import fetch_screener")
print("  from momentum_calculator import is_above_ma200")
print("  from data_fetcher import fetch_prices")
print("  from datetime import datetime, timedelta")
print()
print("  universe = fetch_screener(limit=100)")
print("  above_count = 0")
print("  total = 0")
print()
print("  for symbol in universe['symbol'].head(20):")
print("      end = datetime.now().strftime('%Y-%m-%d')")
print("      start = (datetime.now() - timedelta(days=300)).strftime('%Y-%m-%d')")
print("      prices = fetch_prices(symbol, start, end, use_cache=False)")
print("      if len(prices) >= 200:")
print("          if is_above_ma200(prices):")
print("              above_count += 1")
print("          total += 1")
print()
print("  print(f'{above_count}/{total} sobre MA200 ({100*above_count/total:.1f}%)')")
print("  \"")
print()

print("=" * 80)
